/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsMinifyOptions {
  mangle?: boolean
  compress?: boolean
  sourceMap?: boolean
  filename?: string
  module?: boolean
}
export interface JsMinifyResult {
  code: string
  map?: string
}
export declare function minifyJs(code: string, options?: JsMinifyOptions | undefined | null): JsMinifyResult
export interface CssMinifyOptions {
  filename?: string
  sourceMap?: boolean
}
export interface CssMinifyResult {
  code: string
  map?: string
}
export declare function minifyCss(code: string, options?: CssMinifyOptions | undefined | null): CssMinifyResult
